<?php

namespace AppBundle\Repository;

/**
 * ShoppingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListRepository extends \Doctrine\ORM\EntityRepository
{
}
