// <auto-generated />
namespace _08.Create_User.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DAa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DAa));
        
        string IMigrationMetadata.Id
        {
            get { return "201710281025255_DAa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
